### ISSUE TITLE
sfm software  segfaults

### ISSUE THREAD

**Issue by mribbons** [openMVG/openMVG#1446]
Hi,
I am getting segfaults with the sfm components.

I have compiled with BUILD_TYPE=DEBUG, but I get the same result with BUILD_TYPE=RELEASE.

Running on Ubuntu 16.04

commit 835f1e585377a55d4143548fa9181438f5d23889

cmake:
```sh
$ cmake -DCMAKE_BUILD_TYPE=DEBUG -DOpenMVG_BUILD_TESTS=ON -DOpenMVG_BUILD_GUI_SOFTWARES=OFF  -G "Unix Makefiles" ../openMVG/src/
$ make -j8
```

Test output:
```sh
The following tests FAILED:
         71 - openMVG_test_sfm_data_BA (SEGFAULT)
         75 - openMVG_test_global_SfM (SEGFAULT)
         76 - openMVG_test_sequential_SfM (SEGFAULT)
         77 - openMVG_test_sequential_SfM2 (SEGFAULT)
         78 - openMVG_test_stellar_SfM (SEGFAULT)
Errors while running CTest
```

Castle reconstruction:

```sh
$ python software/SfM/SfM_SequentialPipeline.py ImageDataset_SceauxCastle/images ./Castle_Incremental_Reconstruction
... commands start failing because can't read .bin, so run manually from:

$ openMVG_main_IncrementalSfM 
-i Castle_Incremental_Reconstruction/matches/sfm_data.json -m Castle_Incremental_Reconstruction/matches/ -o Castle_Incremental_Reconstruction/reconstruction_sequential
```

Running same command from gdb:

```gdb
(gdb) bt
#0  0x00000000013ec233 in _mm256_load_pd (__P=0x2492df0)
    at /usr/lib/gcc/x86_64-linux-gnu/5/include/avxintrin.h:836
#1  Eigen::internal::pload<double __vector(4)>(Eigen::internal::unpacket_traits<double __vector(4)>::type const*) (from=0x2492df0)
    at /usr/include/eigen3/Eigen/src/Core/arch/AVX/PacketMath.h:207
#2  0x00000000016344f5 in Eigen::internal::ploadt<double __vector(4), 32>(Eigen::internal::unpacket_traits<double __vector(4)>::type const*) (from=0x2492df0)
    at /usr/include/eigen3/Eigen/src/Core/GenericPacketMath.h:475
#3  Eigen::internal::evaluator<Eigen::PlainObjectBase<Eigen::Matrix<double, -1, 1, 0, -1, 1> > >::packet<32, double __vector(4)>(long) const (
    this=0x7fffffffaaf8, index=0)
    at /usr/include/eigen3/Eigen/src/Core/CoreEvaluators.h:189
#4  0x00000000016641f5 in Eigen::internal::unary_evaluator<Eigen::CwiseUnaryOp<Eigen::internal::scalar_opposite_op<double>, Eigen::Matrix<double, -1, 1, 0, -1, 1> const>, Eigen::internal::IndexBased, double>::packet<32, double __vector(4)>(long) const (this=0x7fffffffaaf0, index=0)
    at /usr/include/eigen3/Eigen/src/Core/CoreEvaluators.h:412
#5  0x000000000165dbb6 in Eigen::internal::generic_dense_assignment_kernel<Eigen::internal::evaluator<Eigen::Matrix<double, -1, 1, 0, -1, 1> >, Eigen::internal::evaluator<Eigen::CwiseUnaryOp<Eigen::internal::scalar_opposite_op<double>, Eigen::Matrix<double, -1, 1, 0, -1, 1> const> >, Eigen::internal::assign_op<double>, 0>::assignPacket<32, 32, double __vector(4)>(long) (this=0x7fffffffab10,
    index=0) at /usr/include/eigen3/Eigen/src/Core/AssignEvaluator.h:598
```

Am I doing something wrong, or should I be using a different version?

**Comment by rperrot** [comment]
There should be two things to test : 
* Ensure you are using internal ceres solver 
* Try to disable AVX (in OptimizeForArchitecture.cmake or disable the call to OptimizeForArchitecture in main cmake)

**Comment by mribbons** [comment]
Option two worked. I am using an old AMD CPU for testing.

I commented out this line, deleted CMakeCache.txt and recompiled:
https://github.com/openMVG/openMVG/blob/master/src/CMakeLists.txt#L104

Thanks!
