### ISSUE TITLE
core dump at SIFT_KeypointExtractor::ComputeDogs

### ISSUE THREAD

**Issue by riematrix** [openMVG/openMVG#1511]
Hi,

I'm trying to use openMVG as a third party lib. The sample provided by openmvg works fine but I got this error in my own project.
```
#0  __GI___libc_free (mem=0xf4251) at malloc.c:2951
#1  0x00000000005159ee in openMVG::features::sift::SIFT_KeypointExtractor::ComputeDogs (this=0x7ffcadffb8f0, octave=...) at /usr/local/include/openMVG/features/sift/sift_KeypointExtractor.hpp:109
#2  0x0000000000515869 in openMVG::features::sift::SIFT_KeypointExtractor::operator() (this=0x7ffcadffb8f0, octave=..., keypoints=std::vector of length 0, capacity 0)
    at /usr/local/include/openMVG/features/sift/sift_KeypointExtractor.hpp:82
#3  0x0000000000517e09 in openMVG::features::SIFT_Anatomy_Image_describer::Describe_SIFT_Anatomy (this=0x1329ca0, image=..., mask=0x0)
    at /usr/local/include/openMVG/features/sift/SIFT_Anatomy_Image_Describer.hpp:176
#4  0x00000000005182c1 in openMVG::features::SIFT_Anatomy_Image_describer::Describe (this=0x1329ca0, image=..., mask=0x0) at /usr/local/include/openMVG/features/sift/SIFT_Anatomy_Image_Describer.hpp:218
#5  0x0000000000512bed in openMVG::features::Image_describer::Describe (this=0x1329ca0, image=..., regions=std::unique_ptr<openMVG::features::Regions> containing 0x0, mask=0x0)
    at /usr/local/include/openMVG/features/image_describer.hpp:60
#6  0x0000000000510294 in main (argc=1, argv=0x7ffcadffbdd8) at /home/zj/exp/slam/Epipolar/t.cpp:80
```
Ububtu 16.04
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
cmake list:

```
CMAKE_MINIMUM_REQUIRED(VERSION 2.6)

SET_PROPERTY(GLOBAL PROPERTY TARGET_SUPPORTS_SHARED_LIBS TRUE)

PROJECT(TP3)

IF(NOT CMAKE_BUILD_TYPE)
  SET(CMAKE_BUILD_TYPE Debug)
ENDIF()


include(CheckCXXCompilerFlag)
CHECK_CXX_COMPILER_FLAG("-std=c++11" COMPILER_SUPPORTS_CXX11)
CHECK_CXX_COMPILER_FLAG("-std=c++0x" COMPILER_SUPPORTS_CXX0X)
if(COMPILER_SUPPORTS_CXX11)
   set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -fopenmp -msse4.1 -mavx2")
   add_definitions(-DCOMPILEDWITHC11)
   message(STATUS "Using flag -std=c++11.")
elseif(COMPILER_SUPPORTS_CXX0X)
   set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++0x -fopenmp -msse4.1 -mavx2")
   add_definitions(-DCOMPILEDWITHC0X)
   message(STATUS "Using flag -std=c++0x.")
else()
   message(FATAL_ERROR "The compiler ${CMAKE_CXX_COMPILER} has no C++11 support. Please use a different C++ compiler.")
endif()

find_package(OpenMP REQUIRED)
if(OPENMP_FOUND)
message("OPENMP FOUND")
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${OpenMP_C_FLAGS}")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${OpenMP_CXX_FLAGS}")
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${OpenMP_EXE_LINKER_FLAGS}")
endif()

set(OpenMVG_DIR "/usr/local/share/openMVG/cmake")
find_package(OpenMVG REQUIRED)
ADD_EXECUTABLE(t t.cpp )
TARGET_LINK_LIBRARIES(t
    openMVG_image
    openMVG_features
    openMVG_matching
    stlplus
    vlsift
    )
set_target_properties( t PROPERTIES CXX_STANDARD 11)

target_compile_definitions(t
  PRIVATE -DTHIS_SOURCE_DIR="${CMAKE_CURRENT_SOURCE_DIR}")
```

Source code:
```
// This file is part of OpenMVG, an Open Multiple View Geometry C++ library.

// Copyright (c) 2015 Pierre MOULON.

// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

#include "openMVG/image/image_io.hpp"
#include "openMVG/image/image_concat.hpp"
#include "openMVG/features/akaze/image_describer_akaze.hpp"
#include "openMVG/features/sift/SIFT_Anatomy_Image_Describer.hpp"
#include "openMVG/features/svg_features.hpp"
#include "openMVG/matching/regions_matcher.hpp"
#include "openMVG/matching/svg_matches.hpp"

//#include "third_party/stlplus3/filesystemSimplified/file_system.hpp"
#include "third_party/cmdLine/cmdLine.h"
#include <memory>
#include <string>

using namespace openMVG;
using namespace openMVG::image;
using namespace std;

int main(int argc, char **argv) {

  // Add options to choose the desired Image_describer
  std::string sImage_describer_type = "SIFT";

  CmdLine cmd;
  cmd.add( make_option('t', sImage_describer_type, "type") );

  try {
      if (argc == 1) throw std::string("Invalid command line parameter.");
      cmd.process(argc, argv);
  } catch (const std::string& s) {
      std::cerr << "Usage: " << argv[0] << '\n'
      << "\n[Optional]\n"
      << "[-t|--type\n"
      << "  (choose an image_describer interface):\n"
      << "   SIFT: SIFT keypoint & descriptor,\n"
      << "   AKAZE: AKAZE keypoint & floating point descriptor]"
      << std::endl;

      std::cerr << s << std::endl;
      return EXIT_FAILURE;
  }

  const string jpg_filenameL = "Ace_0.png";
  const string jpg_filenameR = "Ace_1.png";

  Image<unsigned char> imageL, imageR;
  ReadImage(jpg_filenameL.c_str(), &imageL);
  ReadImage(jpg_filenameR.c_str(), &imageR);
  assert(imageL.data() && imageR.data());

  // Call Keypoint extractor
  using namespace openMVG::features;
  std::unique_ptr<Image_describer> image_describer;
  if (sImage_describer_type == "SIFT")
    image_describer.reset(new SIFT_Anatomy_Image_describer(SIFT_Anatomy_Image_describer::Params()));
  else if (sImage_describer_type == "AKAZE")
    image_describer = AKAZE_Image_describer::create
      (AKAZE_Image_describer::Params(AKAZE::Params(), AKAZE_MSURF));
  else if (sImage_describer_type == "AKAZE_MLDB")
    image_describer = AKAZE_Image_describer::create
      (AKAZE_Image_describer::Params(AKAZE::Params(), AKAZE_MLDB));

  if (image_describer == nullptr)
  {
    std::cerr << "Invalid Image_describer type" << std::endl;
    return EXIT_FAILURE;
  }

  //--
  // Detect regions thanks to the image_describer
  //--
  std::map<IndexT, std::unique_ptr<features::Regions>> regions_perImage;
  image_describer->Describe(imageL, regions_perImage[0]);
  image_describer->Describe(imageR, regions_perImage[1]);

  //--
  // Display used images & Features
  //--

  {
    //- Show images side by side
    Image<unsigned char> concat;
    ConcatH(imageL, imageR, concat);
    const string out_filename = "00_images.jpg";
    WriteImage(out_filename.c_str(), concat);
  }

//  {
//    //- Draw features on the images (side by side)
//    Features2SVG
//    (
//      jpg_filenameL,
//      {imageL.Width(), imageL.Height()},
//      regions_perImage.at(0)->GetRegionsPositions(),
//      jpg_filenameR,
//      {imageR.Width(), imageR.Height()},
//      regions_perImage.at(1)->GetRegionsPositions(),
//      "01_features.svg"
//    );
//  }

  //--
  // Compute corresponding points
  //--
  //-- Perform matching -> find Nearest neighbor, filtered with Distance ratio
  matching::IndMatches vec_PutativeMatches;
  matching::DistanceRatioMatch(
    0.8, matching::BRUTE_FORCE_L2,
    *regions_perImage.at(0).get(),
    *regions_perImage.at(1).get(),
    vec_PutativeMatches);

//  // Draw correspondences after Nearest Neighbor ratio filter
//  {
//    const bool bVertical = true;
//    Matches2SVG
//    (
//      jpg_filenameL,
//      {imageL.Width(), imageL.Height()},
//      regions_perImage.at(0)->GetRegionsPositions(),
//      jpg_filenameR,
//      {imageR.Width(), imageR.Height()},
//      regions_perImage.at(1)->GetRegionsPositions(),
//      vec_PutativeMatches,
//      "02_Matches.svg",
//      bVertical
//    );
//  }

  // Display some statistics
  std::cout
    << regions_perImage.at(0)->RegionCount() << " #Features on image A" << std::endl
    << regions_perImage.at(1)->RegionCount() << " #Features on image B" << std::endl
    << vec_PutativeMatches.size() << " #matches with Distance Ratio filter" << std::endl;

  return EXIT_SUCCESS;
}
```

**Comment by pmoulon** [comment]
For me it could be an alignment issue or some compilation flag that differ.
Flags should come automatically with the targets thanks to cmake transitivity.

Which version are you using?
Are you using master or develop?
Are you on a x86 or x64 platform?

As a temporary solution you can comment this line https://github.com/openMVG/openMVG/blob/master/src/CMakeLists.txt#L104 and rebuild and reinstall openMVG.

**Comment by pmoulon** [comment]
Any feedback?
