### ISSUE TITLE
software/SfM/tutorial_demo.py not working

### ISSUE THREAD

**Issue by sibowsb** [openMVG/openMVG#1539]
Hello,

I ran into the following issue while running `openMVG_Build/software/SfM/tutorial_demo.py`:
```
$ python tutorial_demo.py
Cloning into 'ImageDataset_SceauxCastle'...
remote: Enumerating objects: 17, done.
remote: Total 17 (delta 0), reused 0 (delta 0), pack-reused 17
Unpacking objects: 100% (17/17), done.
Using input dir  :  /Users/sibo/.local/src/openMVG_Build/software/SfM/ImageDataset_SceauxCastle/images
      output_dir :  /Users/sibo/.local/src/openMVG_Build/software/SfM/tutorial_out
1. Intrinsics analysis
Traceback (most recent call last):
  File "tutorial_demo.py", line 49, in <module>
    pIntrisics = subprocess.Popen( [os.path.join(OPENMVG_SFM_BIN, "openMVG_main_SfMInit_ImageListing"),  "-i", input_dir, "-o", matches_dir, "-d", camera_file_params, "-c", "3"] )
  File "/anaconda3/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/anaconda3/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sibo/.local/src/openMVG_Build/Darwin-x86_64-RELEASE/RELEASE/openMVG_main_SfMInit_ImageListing': '/Users/sibo/.local/src/openMVG_Build/Darwin-x86_64-RELEASE/RELEASE/openMVG_main_SfMInit_ImageListing'
```

I tried removing the second `RELEASE/` from `OPENMVG_SFM_BIN`, but I encountered the same problem.

Under `/Users/sibo/.local/src/openMVG_Build/Darwin-x86_64-RELEASE/` only the following entries are present:
```
$ ls /Users/sibo/.local/src/openMVG_Build/Darwin-x86_64-RELEASE/
openMVG_main_AlternativeVO.app			ui_openMVG_MatchesViewer.app
openMVG_sample_describe_and_match_GUI.app
```

I'm using a Mac (10.14.2) and I followed the instruction on [BUILD.md](https://github.com/openMVG/openMVG/blob/master/BUILD.md) to build openMVG -- namely
```
$ git clone --recursive https://github.com/openMVG/openMVG.git
$ mkdir openMVG_Build
$ cd openMVG_Build
$ cmake -DCMAKE_BUILD_TYPE=RELEASE . ../openMVG/src/
```

Please help. Thank you in advance!

**Comment by sibowsb** [comment]
Ah, I forgot to actually `make` and `make install` it after `cmake -DCMAKE_BUILD_TYPE=RELEASE . ../openMVG/src/`. Sorry, I'm dumb.
