### ISSUE TITLE
openMVG and Eigen Align error

### ISSUE THREAD

**Issue by 193769981** [openMVG/openMVG#1828]
Hello, I installed openmvg 1.6 with vcpkg, but when I run triangulatenview, the eigen function "aligned_ Free" will cause an interrupt error. When I use avx2 or add the precompiled header "eigen_ MAX_ ALIGN_ Bytes = 32 "will not cause this problem. Why? thank you!

**Comment by YueLiu-coder** [comment]
Me, too! Please Help Me!

**Comment by 193769981** [comment]
![image](https://user-images.githubusercontent.com/44664739/100051535-18eab700-2e57-11eb-9dcc-26329f128850.png)

**Comment by jujumo** [comment]
Could it be somehow related to the problem I face ?
I successfully compile OpenMVG on an Ubuntu18.04, with ceres and eigen installed systemwide.
But I cant run the pipeline on SceauCasttle images, and  openMVG tests shows some errors:

```
...
57/85 Test #57: openMVG_test_translation_averaging .......................***Exception: SegFault  0.11 sec
75/85 Test #75: openMVG_test_sfm_data_BA .................................***Exception: Child aborted  0.12 sec
81/85 Test #81: openMVG_test_sequential_SfM ..............................***Exception: Child aborted  2.70 sec
82/85 Test #82: openMVG_test_sequential_SfM2 .............................***Exception: Child aborted  0.71 sec
...
```

The problem seems appearing when using ceres solver.
See back trace on  Linux-x86_64-Debug/openMVG_test_sfm_data_BA

```
Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff56e2921 in __GI_abort () at abort.c:79
#2  0x00007ffff572b967 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff5858b0d "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007ffff57329da in malloc_printerr (str=str@entry=0x7ffff585a818 "double free or corruption (out)") at malloc.c:5342
#4  0x00007ffff5739f6a in _int_free (have_lock=0, p=0x555556404c30, av=0x7ffff5a8dc40 <main_arena>) at malloc.c:4308
#5  __GI___libc_free (mem=0x555556404c40) at malloc.c:3134
#6  0x0000555555f38900 in ceres::EigenTypes<-1, -1>::Matrix ceres::internal::InvertPSDMatrix<-1>(bool, ceres::EigenTypes<-1, -1>::Matrix const&) ()
#7  0x0000555555f3953d in ceres::internal::SchurEliminator<2, -1, -1>::Eliminate(ceres::internal::BlockSparseMatrixData const&, double const*, double const*, ceres::internal::BlockRandomAccessMatrix*, double*)::{lambda(int, int)#2}::operator()(int, int) const ()
#8  0x0000555555dff629 in ceres::internal::ParallelFor(ceres::internal::ContextImpl*, int, int, int, std::function<void (int, int)> const&) ()
#9  0x0000555555f2fd70 in ceres::internal::SchurEliminator<2, -1, -1>::Eliminate(ceres::internal::BlockSparseMatrixData const&, double const*, double const*, ceres::internal::BlockRandomAccessMatrix*, double*) ()
#10 0x0000555555e7e828 in ceres::internal::SchurComplementSolver::SolveImpl(ceres::internal::BlockSparseMatrix*, double const*, ceres::internal::LinearSolver::PerSolveOptions const&, double*) ()
#11 0x0000555555e609f5 in ceres::internal::TypedLinearSolver<ceres::internal::BlockSparseMatrix>::Solve(ceres::internal::LinearOperator*, double const*, ceres::internal::LinearSolver::PerSolveOptions const&, double*) ()
#12 0x0000555555e4b33a in ceres::internal::LevenbergMarquardtStrategy::ComputeStep(ceres::internal::TrustRegionStrategy::PerSolveOptions const&, ceres::internal::SparseMatrix*, double const*, double*) ()
#13 0x0000555555e260c5 in ceres::internal::TrustRegionMinimizer::ComputeTrustRegionStep() ()
#14 0x0000555555e2aa71 in ceres::internal::TrustRegionMinimizer::Minimize(ceres::internal::Minimizer::Options const&, double*, ceres::Solver::Summary*) ()
#15 0x0000555555df9606 in ceres::Solver::Solve(ceres::Solver::Options const&, ceres::Problem*, ceres::Solver::Summary*) ()
#16 0x0000555555dfa1b9 in ceres::Solve(ceres::Solver::Options const&, ceres::Problem*, ceres::Solver::Summary*) ()
#17 0x0000555555c54a5f in openMVG::sfm::Bundle_Adjustment_Ceres::Adjust (this=0x5555563eee90, sfm_data=..., options=...) at /local/devel/openMVG/src/openMVG/sfm/sfm_data_BA_ceres.cpp:475
#18 0x0000555555bf867c in BUNDLE_ADJUSTMENT_EffectiveMinimization_Pinhole_PosePriors_Test::run (this=0x5555563d05c0 <BUNDLE_ADJUSTMENT_EffectiveMinimization_Pinhole_PosePriorsInstance>, 
    result_=...) at /local/devel/openMVG/src/openMVG/sfm/sfm_data_BA_test.cpp:255
#19 0x0000555555ce3b04 in TestRegistry::run (this=0x5555563d0608 <TestRegistry::instance()::registry>, result=...) at /local/devel/openMVG/src/third_party/CppUnitLite/TestRegistry.cpp:45
#20 0x0000555555ce39e1 in TestRegistry::runAllTests (result=...) at /local/devel/openMVG/src/third_party/CppUnitLite/TestRegistry.cpp:16
#21 0x0000555555bfa4f8 in main () at /local/devel/openMVG/src/openMVG/sfm/sfm_data_BA_test.cpp:468


The problem disappear when I force the use of internal `eigen`, `cereal` and `ceres`, by manually editing `src/CMakeLists.txt`.

Is there some more elegant way to solve this ?

**Comment by pmoulon** [comment]
@jujumo You must ensure to use the same Eigen version for Ceres and OpenMVG when you are compiling your own ceres

**Comment by YueLiu-coder** [comment]
> @jujumo You must ensure to use the same Eigen version for Ceres and OpenMVG when you are compiling your own ceres

Thanks. We have given up the party of PCL which is in conflict with OpenMVG, and coding by ourselves.

**Comment by YueLiu-coder** [comment]
By the way, OpenMVG is beautiful.

**Comment by pmoulon** [comment]
Closing the issue, and thank you for your last comment.
Have fun with OpenMVG and don't hesistate to share in github discussion some screenshot about your reconstruction
