### ISSUE TITLE
Runtime errors on latest build for incremental SfM pipeline

### ISSUE THREAD

**Issue by johnwlambert** [openMVG/openMVG#1939]
Hi, I get a few errors when I run the sequential OpenMVG pipeline. Could you take a look?

1. After building the latest, I get `No such file or directory: openMVG_main_ComputeStructureFromKnownPoses'`
2. After building latest, I see `levenberg_marquardt_strategy.cc:115] Linear solver failure. Failed to compute a step: Eigen failure. Unable to perform dense Cholesky factorization.`

```
SequentialSfMReconstructionEngine::ComputeResidualsMSE.
	-- #Tracks:	14362
	-- Residual min:	3.60268e-07
	-- Residual median:	0.214436
	-- Residual max:	 3.95531
	-- Residual mean:	 0.335412

Histogram of residuals:
0	|	70307
0.396	|	19123
0.791	|	5824
1.19	|	2277
1.58	|	941
1.98	|	434
2.37	|	230
2.77	|	119
3.16	|	67
3.56	|	25
3.96


 Total Ac-Sfm took (s): 12
...Generating SfM_Report.html
...Export SfM_Data to disk.
5. Colorize Structure

Compute scene structure color
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
6. Structure from Known Poses (robust triangulation)
Traceback (most recent call last):
  File "SfM_SequentialPipeline.py", line 75, in <module>
    pRecons = subprocess.Popen( [os.path.join(OPENMVG_SFM_BIN, "openMVG_main_ComputeStructureFromKnownPoses"),  "-i", reconstruction_dir+"/sfm_data.bin", "-m", matches_dir, "-f", os.path.join(matches_dir, "matches.f.bin"), "-o", os.path.join(reconstruction_dir,"robust.bin")] )
  File "/Users/johnlam/opt/miniconda3/envs/gtsfm-v1/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/johnlam/opt/miniconda3/envs/gtsfm-v1/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/johnlam/Downloads/openMVG_Build/Darwin-x86_64-RELEASE/openMVG_main_ComputeStructureFromKnownPoses'
```

I also see:
```
Automatic selection of an initial pair:
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
A-Contrario initial pair residual: 103.283
WARNING: Logging before InitGoogleLogging() is written to STDERR
W20211001 12:48:12.164855 217210368 levenberg_marquardt_strategy.cc:115] Linear solver failure. Failed to compute a step: Eigen failure. Unable to perform dense Cholesky factorization.
W20211001 12:48:12.165700 217210368 levenberg_marquardt_strategy.cc:115] Linear solver failure. Failed to compute a step: Eigen failure. Unable to perform dense Cholesky factorization.
W20211001 12:48:12.165786 217210368 levenberg_marquardt_strategy.cc:115] Linear solver failure. Failed to compute a step: Eigen failure. Unable to perform dense Cholesky factorization.
W20211001 12:48:12.166646 217210368 levenberg_marquardt_strategy.cc:115] Linear solver failure. Failed to compute a step: Eigen failure. Unable to perform dense Cholesky factorization.
W20211001 12:48:12.167004 217210368 levenberg_marquardt_strategy.cc:115] Linear solver failure. Failed to compute a step: Eigen failure. Unable to perform dense Cholesky factorization.
W20211001 12:48:12.167356 217210368 levenberg_marquardt_strategy.cc:115] Linear solver failure. Failed to compute a step: Eigen failure. Unable to perform dense Cholesky factorization.
W20211001 12:48:12.167439 217210368 levenberg_marquardt_strategy.cc:115] Linear solver failure. Failed to compute a step: Eigen failure. Unable to perform dense Cholesky factorization.
W20211001 12:48:12.168056 217210368 levenberg_marquardt_strategy.cc:115] Linear solver failure. Failed to compute a step: Eigen failure. Unable to perform dense Cholesky factorization.
W20211001 12:48:12.168807 217210368 levenberg_marquardt_strategy.cc:115] Linear solver failure. Failed to compute a step: Eigen failure. Unable to perform dense Cholesky factorization.
W20211001 12:48:12.169157 217210368 levenberg_marquardt_strategy.cc:115] Linear solver failure. Failed to compute a step: Eigen failure. Unable to perform dense Cholesky factorization.
W20211001 12:48:12.169900 217210368 levenberg_marquardt_strategy.cc:115] Linear solver failure. Failed to compute a step: Eigen failure. Unable to perform dense Cholesky factorization.
W20211001 12:48:12.169982 217210368 levenberg_marquardt_strategy.cc:115] Linear solver failure. Failed to compute a step: Eigen failure. Unable to perform dense Cholesky factorization.
W20211001 12:48:12.170331 217210368 levenberg_marquardt_strategy.cc:115] Linear solver failure. Failed to compute a step: Eigen failure. Unable to perform dense Cholesky factorization.
W20211001 12:48:12.170683 217210368 levenberg_marquardt_strategy.cc:115] Linear solver failure. Failed to compute a step: Eigen failure. Unable to perform dense Cholesky factorization.
W20211001 12:48:12.171037 217210368 levenberg_marquardt_strategy.cc:115] Linear solver failure. Failed to compute a step: Eigen failure. Unable to perform dense Cholesky factorization.
W20211001 12:48:12.171119 217210368 levenberg_marquardt_strategy.cc:115] Linear solver failure. Failed to compute a step: Eigen failure. Unable to perform dense Cholesky factorization.
W20211001 12:48:12.171468 217210368 levenberg_marquardt_strategy.cc:115] Linear solver failure. Failed to compute a step: Eigen failure. Unable to perform dense Cholesky factorization.

Bundle Adjustment statistics (approximated RMSE):
 #views: 2
 #poses: 2
 #intrinsics: 1
 #tracks: 180
 #residuals: 720
 Initial RMSE: 7.22236
 Final RMSE: 6.79117
 Time (s): 0.0154788

```

**Comment by johnwlambert** [comment]
When I look at the built binaries, I see: 
```
Darwin-x86_64-RELEASE % ls -l
total 295736
-rw-r--r--  1 johnlam  staff   477984 Sep 13 12:07 libdomset.a
-rw-r--r--  1 johnlam  staff  2273976 Sep 13 11:52 liblib_CoinUtils.a
-rw-r--r--  1 johnlam  staff   514968 Sep 13 11:52 liblib_Osi.a
-rw-r--r--  1 johnlam  staff   365016 Sep 13 11:53 liblib_OsiClpSolver.a
-rw-r--r--  1 johnlam  staff  3318272 Sep 13 11:53 liblib_clp.a
-rw-r--r--  1 johnlam  staff    17880 Sep 13 11:53 libopenMVG_easyexif.a
-rw-r--r--  1 johnlam  staff    31024 Sep 13 11:53 libopenMVG_exif.a
-rw-r--r--  1 johnlam  staff    96224 Sep 13 11:53 libopenMVG_fast.a
-rw-r--r--  1 johnlam  staff  1112424 Sep 13 11:54 libopenMVG_features.a
-rw-r--r--  1 johnlam  staff   969952 Sep 13 11:58 libopenMVG_geometry.a
-rw-r--r--  1 johnlam  staff   107352 Sep 13 11:54 libopenMVG_image.a
-rw-r--r--  1 johnlam  staff    61000 Sep 13 11:58 libopenMVG_kvld.a
-rw-r--r--  1 johnlam  staff   182376 Sep 13 11:57 libopenMVG_lInftyComputerVision.a
-rw-r--r--  1 johnlam  staff   150080 Sep 13 11:53 libopenMVG_lemon.a
-rw-r--r--  1 johnlam  staff    27400 Sep 13 11:54 libopenMVG_linearProgramming.a
-rw-r--r--  1 johnlam  staff  1386680 Sep 13 11:58 libopenMVG_matching.a
-rw-r--r--  1 johnlam  staff   140248 Sep 13 11:59 libopenMVG_matching_image_collection.a
-rw-r--r--  1 johnlam  staff  2761136 Sep 13 11:57 libopenMVG_multiview.a
-rw-r--r--  1 johnlam  staff    64312 Sep 13 11:59 libopenMVG_multiview_test_data.a
-rw-r--r--  1 johnlam  staff   321200 Sep 13 11:54 libopenMVG_numeric.a
-rw-r--r--  1 johnlam  staff    28408 Sep 13 11:59 libopenMVG_robust_estimation.a
-rw-r--r--  1 johnlam  staff  5354696 Sep 13 12:02 libopenMVG_sfm.a
-rw-r--r--  1 johnlam  staff    68712 Sep 13 11:53 libopenMVG_stlplus.a
-rw-r--r--  1 johnlam  staff     5048 Sep 13 11:59 libopenMVG_system.a
-rw-r--r--  1 johnlam  staff   114400 Sep 13 12:04 libvlsift.a
-rwxr-xr-x  1 johnlam  staff    79288 Sep 13 11:53 main_svgSample
-rwxr-xr-x  1 johnlam  staff  1873872 Sep 13 12:07 openMVG_main_ChangeLocalOrigin
-rwxr-xr-x  1 johnlam  staff  5545160 Sep 13 12:09 openMVG_main_ColHarmonize
-rwxr-xr-x  1 johnlam  staff  2231096 Sep 13 12:07 openMVG_main_ComputeClusters
-rwxr-xr-x  1 johnlam  staff  2857912 Sep 13 12:07 openMVG_main_ComputeFeatures
-rwxr-xr-x  1 johnlam  staff  4204000 Sep 13 12:07 openMVG_main_ComputeMatches
-rwxr-xr-x  1 johnlam  staff  1961992 Sep 13 12:05 openMVG_main_ComputeSfM_DataColor
-rwxr-xr-x  1 johnlam  staff  1895216 Sep 13 12:06 openMVG_main_ConvertList
-rwxr-xr-x  1 johnlam  staff   178832 Sep 13 12:07 openMVG_main_ConvertMatches
-rwxr-xr-x  1 johnlam  staff  1851056 Sep 13 12:06 openMVG_main_ConvertSfM_DataFormat
-rwxr-xr-x  1 johnlam  staff  5496368 Sep 13 12:07 openMVG_main_ExportCameraFrustums
-rwxr-xr-x  1 johnlam  staff  1966472 Sep 13 12:08 openMVG_main_ExportUndistortedImages
-rwxr-xr-x  1 johnlam  staff  5498808 Sep 13 12:05 openMVG_main_FrustumFiltering
-rwxr-xr-x  1 johnlam  staff  7659224 Sep 13 12:06 openMVG_main_GlobalSfM
-rwxr-xr-x  1 johnlam  staff  3913312 Sep 13 12:06 openMVG_main_IncrementalSfM
-rwxr-xr-x  1 johnlam  staff  4200816 Sep 13 12:06 openMVG_main_IncrementalSfM2
-rwxr-xr-x  1 johnlam  staff  1899304 Sep 13 12:06 openMVG_main_ListMatchingPairs
-rwxr-xr-x  1 johnlam  staff  2208416 Sep 13 12:07 openMVG_main_MatchesToTracks
-rwxr-xr-x  1 johnlam  staff  1917704 Sep 13 12:06 openMVG_main_PointsFiltering
-rwxr-xr-x  1 johnlam  staff  2046536 Sep 13 12:07 openMVG_main_SfMInit_ImageListing
-rwxr-xr-x  1 johnlam  staff  2069616 Sep 13 12:09 openMVG_main_SfMInit_ImageListingFromKnownPoses
-rwxr-xr-x  1 johnlam  staff  4615736 Sep 13 12:09 openMVG_main_SfM_Localization
-rwxr-xr-x  1 johnlam  staff  1955472 Sep 13 12:05 openMVG_main_SplitMatchFileIntoMatchFiles
-rwxr-xr-x  1 johnlam  staff  2521232 Sep 13 12:06 openMVG_main_evalQuality
-rwxr-xr-x  1 johnlam  staff   104128 Sep 13 12:04 openMVG_main_exif_Parsing
-rwxr-xr-x  1 johnlam  staff  2186544 Sep 13 12:09 openMVG_main_exportKeypoints
-rwxr-xr-x  1 johnlam  staff  2210432 Sep 13 12:08 openMVG_main_exportMatches
-rwxr-xr-x  1 johnlam  staff  2229744 Sep 13 12:08 openMVG_main_exportTracks
-rwxr-xr-x  1 johnlam  staff  2422200 Sep 13 12:09 openMVG_main_geodesy_registration_to_gps_position
-rwxr-xr-x  1 johnlam  staff  1871240 Sep 13 12:08 openMVG_main_openMVG2Agisoft
-rwxr-xr-x  1 johnlam  staff  1981224 Sep 13 12:08 openMVG_main_openMVG2CMPMVS
-rwxr-xr-x  1 johnlam  staff  1982960 Sep 13 12:08 openMVG_main_openMVG2Colmap
-rwxr-xr-x  1 johnlam  staff  1892872 Sep 13 12:08 openMVG_main_openMVG2MESHLAB
-rwxr-xr-x  1 johnlam  staff  1961640 Sep 13 12:08 openMVG_main_openMVG2MVE2
-rwxr-xr-x  1 johnlam  staff  1851104 Sep 13 12:08 openMVG_main_openMVG2MVSTEXTURING
-rwxr-xr-x  1 johnlam  staff  1980120 Sep 13 12:09 openMVG_main_openMVG2NVM
-rwxr-xr-x  1 johnlam  staff  2000320 Sep 13 12:08 openMVG_main_openMVG2PMVS
-rwxr-xr-x  1 johnlam  staff  5576656 Sep 13 12:09 openMVG_main_openMVG2WebGL
-rwxr-xr-x  1 johnlam  staff  1982504 Sep 13 12:08 openMVG_main_openMVG2openMVS
-rwxr-xr-x  1 johnlam  staff  1986728 Sep 13 12:08 openMVG_main_openMVGSpherical2Cubic
-rwxr-xr-x  1 johnlam  staff   290920 Sep 13 12:02 openMVG_sample_cameras_undistoBrown
-rwxr-xr-x  1 johnlam  staff   528152 Sep 13 12:04 openMVG_sample_features_affine
-rwxr-xr-x  1 johnlam  staff  1320352 Sep 13 12:05 openMVG_sample_features_kvld
-rwxr-xr-x  1 johnlam  staff  1260448 Sep 13 12:05 openMVG_sample_features_siftPutative
-rwxr-xr-x  1 johnlam  staff   175240 Sep 13 12:05 openMVG_sample_geodesy_show_exif_gps_position
-rwxr-xr-x  1 johnlam  staff  1431152 Sep 13 12:05 openMVG_sample_image_matching
-rwxr-xr-x  1 johnlam  staff  1452288 Sep 13 12:05 openMVG_sample_image_matching_gmsfilter
-rwxr-xr-x  1 johnlam  staff  1542920 Sep 13 12:04 openMVG_sample_main_features_repeatability_dataset
-rwxr-xr-x  1 johnlam  staff  2040616 Sep 13 12:03 openMVG_sample_multiview_robustEssential
-rwxr-xr-x  1 johnlam  staff  4256872 Sep 13 12:04 openMVG_sample_multiview_robustEssential_ba
-rwxr-xr-x  1 johnlam  staff  3851128 Sep 13 12:04 openMVG_sample_multiview_robustEssential_spherical
-rwxr-xr-x  1 johnlam  staff  1492352 Sep 13 12:03 openMVG_sample_multiview_robustFundamental
-rwxr-xr-x  1 johnlam  staff  1512808 Sep 13 12:03 openMVG_sample_multiview_robustFundamental_guided
-rwxr-xr-x  1 johnlam  staff  1572264 Sep 13 12:03 openMVG_sample_multiview_robustHomography
-rwxr-xr-x  1 johnlam  staff  1589984 Sep 13 12:03 openMVG_sample_multiview_robustHomography_guided
-rwxr-xr-x  1 johnlam  staff   298120 Sep 13 12:05 openMVG_sample_pano_converter
-rwxr-xr-x  1 johnlam  staff   223776 Sep 13 12:05 openMVG_sample_pano_spherical_to_cubic
-rwxr-xr-x  1 johnlam  staff  1590576 Sep 13 12:02 openMVG_sample_robust_estimation_Homography
```

**Comment by pmoulon** [comment]
Hello @johnwlambert,
This is weird
Can you try this?
`make openMVG_main_ComputeStructureFromKnownPoses`
And let us know what make is saying

FYI the message `levenberg_marquardt_strategy.cc:115] Linear solver failure.` appears because you use an external ceres, and we don't auto configure glog in openMVG.
- You see that the BA is still successful, just some steps were not valid

**Comment by pmoulon** [comment]
Closing due to lack of feedback, feel free to reopen,
