### ISSUE TITLE
OpenMVG + OpenMVS python pipeline

### ISSUE THREAD

**Issue by FlachyJoe** [openMVG/openMVG#619]
Hi,
I'm happy to share a Python pipeline to proceed a reconstruction with OpenMVG and OpenMVS.
You can basically call `python MvgMvs_Pipeline.py input_dir ouput_dir` or set arguments for each step from the command line (no script editing needed).
This script has been tested under linux and you may adjust binary paths at lines 50+.

[MvgMvs_Pipeline.py.txt](https://github.com/openMVG/openMVG/files/439364/MvgMvs_Pipeline.py.txt)

**Comment by pmoulon** [comment]
Hi @FlachyJoe 

Thank you for this running script.

I just want to point to you that you run some step that are not useful in the process:
#	5. Structure from Known Poses	 openMVG_main_ComputeStructureFromKnownPoses
#	6. Colorized robust triangulation	 openMVG_main_ComputeSfM_DataColor

I mean the results of the step 5 & 6 are not used later on by the process. They are logging less outliers in the resulting scene.

It would be cool also to have an option to allow running Sequential SfM or Global SfM.

**Comment by FlachyJoe** [comment]
You're right, I'd like to give the possibility to obtain all available steps from OpenMVG but my steps selection needs improvements.

**Comment by petern3** [comment]
Since I modified the script, I might as well upload it as well.
[MvgMvs_Pipeline.zip](https://github.com/openMVG/openMVG/files/664720/MvgMvs_Pipeline.zip)

It is basically the same with these changes:
- It works on python 2 and 3
- The paths are different on Windows and Linux
- It won't break if --last-step is too large
- Steps 4,5,6 ("Colorize Structure", "Structure from Know Poses" and "Colorized robust Triangulation") were commented, but OpenMVS "TextureMesh" was inserted at the end
- I changed the parameters in step 1 and 8 to get better results. It may take longer, I didn't time.

This was tested on Windows 10 x64, and you still may need to change the paths by line 50. The OpenMVS_sample-0.7 release was used because I had issues compiling it.

@pmoulon - what is the difference between robust.bin and sfm_data.bin? I can use either to convert to .mvs, except robust.bin takes another step.

**Comment by bigTailHao** [comment]
@FlachyJoe @pmoulon @petern3 @Meekohi @rory             
![image](https://user-images.githubusercontent.com/30993706/43504584-97a54594-9596-11e8-87e2-e5b983026e14.png)
I can manually make sfm_data.bin with official data,but get nothing after Densify point cloud. However,get the right result with the download sfm_data.bin. I debug openMVS, find there is different version id between them.              I would like to get the exe of openMVG and the parampter of openMVS to run it.

**Comment by MasaruPutut** [comment]
I want to try this script but in the 8th step, there is an error for subprocess.Popen(cmdline)
This is the code :
`Traceback (most recent call last):
  File "MvgMvs_Pipeline.py", line 232, in <module>
    pStep = subprocess.Popen(cmdline)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory`

Do you know how to solve this?

**Comment by Liyaguan** [comment]
@petern3 Hello, what is the reason for this?
'C:/openMVS/build/openMVG/Windows-AMD64-Release/Release\openMVG_main_SfMInit_ImageListing' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by pmoulon** [comment]
@Liyaguan Can you translate to English to make it more accessible to the community?
