### ISSUE TITLE
Python scripts fail on Linux

### ISSUE THREAD

**Issue by bkjohnson** [openMVG/openMVG#984]
First, I realize that my issue isn't a problem with openMVG itself, but I'm wondering if there are other Linux users who have encountered it and how they resolved it.

I was able to build openMVG and all the tests pass, but I've tried running `tutorial_demo.py`,  `SfM_GlobalPipeline.py`, and `SfM_SequentialPipeline.py` inside of `openMVG_Build/software/SfM/` and they all fail.  I've tried using python 2.7 as well as 3.5 and it doesn't make much difference.  Here is what I get after running `python tutorial_demo.py`:

```
Cloning into 'ImageDataset_SceauxCastle'...
remote: Counting objects: 17, done.
remote: Total 17 (delta 0), reused 0 (delta 0), pack-reused 17
Unpacking objects: 100% (17/17), done.
Checking connectivity... done.
('Using input dir  : ', '/home/brooks/Projects/openMVG_Build/software/SfM/ImageDataset_SceauxCastle/images')
('      output_dir : ', '/home/brooks/Projects/openMVG_Build/software/SfM/tutorial_out')
1. Intrinsics analysis
 You called : 
/home/brooks/Projects/openMVG_Build/Linux-x86_64-RELEASE/openMVG_main_SfMInit_ImageListing
--imageDirectory /home/brooks/Projects/openMVG_Build/software/SfM/ImageDataset_SceauxCastle/images
--sensorWidthDatabase /home/brooks/Projects/openMVG/src/software/SfM/../../openMVG/exif/sensor_width_database/sensor_width_camera_database.txt
--outputDirectory /home/brooks/Projects/openMVG_Build/software/SfM/tutorial_out/matches
--focal -1
--intrinsics 
--camera_model 3
--group_camera_model 1

- Image listing -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

Warning & Error messages:
K.txt: Unkown image file format.
Readme.txt: Unkown image file format.


SfMInit_ImageListing report:
listed #File(s): 13
usable #File(s) listed in sfm_data: 11
usable #Intrinsic(s) listed in sfm_data: 1
2. Compute features
Traceback (most recent call last):
  File "tutorial_demo.py", line 53, in <module>
    pFeatures = subprocess.Popen( [os.path.join(OPENMVG_SFM_BIN, "openMVG_main_ComputeFeatures"),  "-i", matches_dir+"/sfm_data.json", "-o", matches_dir, "-m", "SIFT", "-f" , "1"] )
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error
```
Here is the output using `python3`, it's pretty similar:

```
Using input dir  :  /home/brooks/Projects/openMVG_Build/software/SfM/ImageDataset_SceauxCastle/images
      output_dir :  /home/brooks/Projects/openMVG_Build/software/SfM/tutorial_out
1. Intrinsics analysis
 You called : 
/home/brooks/Projects/openMVG_Build/Linux-x86_64-RELEASE/openMVG_main_SfMInit_ImageListing
--imageDirectory /home/brooks/Projects/openMVG_Build/software/SfM/ImageDataset_SceauxCastle/images
--sensorWidthDatabase /home/brooks/Projects/openMVG/src/software/SfM/../../openMVG/exif/sensor_width_database/sensor_width_camera_database.txt
--outputDirectory /home/brooks/Projects/openMVG_Build/software/SfM/tutorial_out/matches
--focal -1
--intrinsics 
--camera_model 3
--group_camera_model 1

- Image listing -
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************

Warning & Error messages:
K.txt: Unkown image file format.
Readme.txt: Unkown image file format.


SfMInit_ImageListing report:
listed #File(s): 13
usable #File(s) listed in sfm_data: 11
usable #Intrinsic(s) listed in sfm_data: 1
2. Compute features
Traceback (most recent call last):
  File "tutorial_demo.py", line 53, in <module>
    pFeatures = subprocess.Popen( [os.path.join(OPENMVG_SFM_BIN, "openMVG_main_ComputeFeatures"),  "-i", matches_dir+"/sfm_data.json", "-o", matches_dir, "-m", "SIFT", "-f" , "1"] )
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 8] Exec format error
```

All of the python files are failing at the same spot at step 2.  Since I was able to build everything I feel like this either has to with my version of Linux (Mint 18.2) or my installation of Python.  Any idea how to start fixing this?

**Comment by pmoulon** [comment]
Can you check if the binary `openMVG_main_ComputeFeatures` have been compiled?

**Comment by bkjohnson** [comment]
Yes, it looks like it's been compiled.  Here's the result of a `make` (it happens at ~95%):

```
[  0%] Built target openMVG_system
[ 11%] Built target lib_CoinUtils
[ 14%] Built target lib_Osi
[ 23%] Built target lib_clp
[ 25%] Built target lib_OsiClpSolver
[ 25%] Built target stlplus
[ 28%] Built target lemon
[ 39%] Built target cxsparse
[ 67%] Built target ceres
[ 69%] Built target fast
[ 70%] Built target openMVG_features
[ 70%] Built target openMVG_linearProgramming
[ 71%] Built target openMVG_lInftyComputerVision
[ 74%] Built target openMVG_geometry
[ 74%] Built target openMVG_matching
[ 76%] Built target openMVG_numeric
[ 80%] Built target openMVG_multiview
[ 84%] Built target openMVG_sfm
[ 84%] Built target openMVG_main_evalQuality
[ 84%] Built target openMVG_main_ExportCameraFrustums
[ 84%] Built target openMVG_main_ComputeStructureFromKnownPoses
[ 85%] Built target openMVG_main_FrustumFiltering
[ 85%] Built target openMVG_image
[ 85%] Built target openMVG_main_GlobalSfM
[ 85%] Built target openMVG_main_IncrementalSfM
[ 85%] Built target openMVG_main_ComputeSfM_DataColor
[ 85%] Built target easyexif
[ 85%] Built target openMVG_main_SfMInit_ImageListing
[ 87%] Built target openMVG_matching_image_collection
[ 88%] Built target openMVG_main_ComputeMatches
[ 90%] Built target openMVG_main_ListMatchingPairs
[ 90%] Built target openMVG_main_ConvertSfM_DataFormat
[ 90%] Built target openMVG_main_openMVG2NVM
[ 90%] Built target openMVG_main_openMVG2PMVS
[ 91%] Built target openMVG_main_openMVG2openMVS
[ 92%] Built target openMVG_main_openMVG2MVSTEXTURING
[ 95%] Built target vlsift
[ 95%] Built target openMVG_main_ComputeFeatures
[ 95%] Built target openMVG_main_PointsFiltering
[ 95%] Built target openMVG_main_exportKeypoints
[ 97%] Built target openMVG_main_ConvertList
[ 98%] Built target openMVG_main_exportMatches
[ 98%] Built target openMVG_main_openMVG2MVE2
[ 98%] Built target openMVG_main_exportTracks
[100%] Built target openMVG_main_openMVG2CMPMVS
[100%] Built target openMVG_main_ExportUndistortedImages
[100%] Built target openMVG_main_openMVG2MESHLAB
[100%] Built target domset
[100%] Built target openMVG_main_ComputeClusters
```

**Comment by pmoulon** [comment]
Can you try to launch it manually with the same parameter in the command line in order to see the log.

`openMVG_main_ComputeFeatures -i /home/brooks/Projects/openMVG_Build/software/SfM/tutorial_out/matches/sfm_data.json -o /home/brooks/Projects/openMVG_Build/software/SfM/tutorial_out/matches`

**Comment by bkjohnson** [comment]
There are no errors or other kind of logging output.  I ran it with the full path:

```
/home/brooks/Projects/openMVG_Build/Linux-x86_64-RELEASE/openMVG_main_ComputeFeatures -i /home/brooks/Projects/openMVG_Build/software/SfM/tutorial_out/matches/sfm_data.json -o /home/brooks/Projects/openMVG_Build/software/SfM/tutorial_out/matches/
```

**Comment by bkjohnson** [comment]
I ended up removing `openMVG_Build` and starting from scratch, and that worked!  Something must have been wrong with the original binary, I have no idea what could have happened though.
